# fly.toml app configuration file generated for twitch-clone on 2024-10-04T17:03:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twitch-clone'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[deploy]
release_command = '/app/bin/migrate'

[env]
PHX_HOST = 'twitch-clone.fly.dev'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[services]]
internal_port = 1935
protocol = "tcp"
[[services.ports]]
port = 1935

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1